export const GOT_GEM_ON_SALE = 'GOT_GEM_ON_SALE';
export const GOT_SALES = 'GOT_SALES';
export const GOT_SALES_POPULATED = 'GOT_SALES_POPULATED';

export const CLEAR_STATE = 'CLEAR_STATE';
export const CLEAR_GEM_ON_SALE = 'CLEAR_GEM_ON_SALE';
