const QUERY_KEYS = {
  GEM: 'GEM',
  GEM_ON_SALE: 'GEM_ON_SALE',
  SALES_POPULATED: 'SALES_POPULATED',
  GEMS_FOR_OWNER: 'GEMS_FOR_OWNER',
  GET_PROFILE: 'GET_PROFILE',
  GET_IMAGE_DATA: 'GET_IMAGE_DATA',
};

export default QUERY_KEYS;
